# -*- coding: utf-8 -*-
"""Speech2Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAyoSiMDXID1WQJd3nrhLnokVbsRWeZn
"""

import streamlit as st
from yt_dlp import YoutubeDL
# from pytube import YouTube
import whisper
from deep_translator import GoogleTranslator
import tempfile
import os

# Load Whisper model
model = whisper.load_model("base")

st.title("🎵 YouTube Song to Telugu Lyrics Generator")

# Input YouTube URL
url = st.text_input("Enter YouTube Song URL:")

if url:
    try:
        yt = YoutubeDL(url)
        st.write(f"**Title:** {yt.title}")

        # Download audio
        with tempfile.TemporaryDirectory() as tmpdir:
            audio_file = yt.streams.filter(only_audio=True).first().download(output_path=tmpdir)

            st.info("Extracting lyrics from audio...")

            # Transcribe using Whisper
            result = model.transcribe(audio_file, language="en")
            lyrics = result["text"]

            st.success("Lyrics extracted successfully!")
            st.text_area("Extracted Lyrics (English):", lyrics, height=200)

            # Translate to Telugu
            st.info("Translating to Telugu...")
            telugu_lyrics = GoogleTranslator(source="auto", target="te").translate(lyrics)

            st.text_area("Translated Lyrics (Telugu):", telugu_lyrics, height=200)

            # Download button
            tmp_file = os.path.join(tmpdir, "lyrics_telugu.txt")
            with open(tmp_file, "w", encoding="utf-8") as f:
                f.write(telugu_lyrics)

            with open(tmp_file, "rb") as f:
                st.download_button(
                    label="📥 Download Telugu Lyrics",
                    data=f,
                    file_name="lyrics_telugu.txt",
                    mime="text/plain"
                )
    except Exception as e:
        st.error(f"Error: {e}")
